#  See https://pre-commit.com for more information
#  See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        name: pre-commit-hooks/check-added-large-files
      - id: check-executables-have-shebangs
        name: pre-commit-hooks/check-executables-have-shebangs
      - id: check-json
        name: pre-commit-hooks/check-json
      - id: check-merge-conflict
        name: pre-commit-hooks/check-merge-conflict
        args: [--assume-in-merge]
      - id: check-shebang-scripts-are-executable
        name: pre-commit-hooks/check-shebang-scripts-are-executable
      - id: check-symlinks
        name: pre-commit-hooks/check-symlinks
      - id: check-toml
        name: pre-commit-hooks/check-toml
      - id: check-xml
        name: pre-commit-hooks/check-xml
      - id: check-yaml
        name: pre-commit-hooks/check-yaml
      - id: destroyed-symlinks
        name: pre-commit-hooks/destroyed-symlinks
      - id: end-of-file-fixer
        name: pre-commit-hooks/end-of-file-fixer
      - id: fix-byte-order-marker
        name: pre-commit-hooks/fix-byte-order-marker
      - id: fix-encoding-pragma
        name: pre-commit-hooks/fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
        name: pre-commit-hooks/mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
        name: pre-commit-hooks/trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py311-plus, --keep-runtime-typing]

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.14
    hooks:
      - id: vulture

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        name: yesqa
