name: Build

env:
  RELEASE_VERSION:

on:
  workflow_dispatch

jobs:
  linux-build:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up libraries
        run: |
          python -m pip install wheel pyinstaller
          python -m pip install .

      - name: Build
        run: pyinstaller --icon logo/logo.ico -F __main__.py -n nyaaup

      - name: Create changelog file
        run: python -c "print('\n'.join(open('changelog.md', 'r').read().split('\n\n# nyaaup')[0].split('\n')[1:]))" >> changelog.txt

      - name: Fetch changelog and version
        run: |
          version=$(python -c "print(open('changelog.md', 'r').read().split('\n')[0].split(' ')[2].replace(':', ''))")
          changelog=$(cat changelog.txt)
          echo -e "Version: $version\n\nChangelog:\n$changelog"
          echo "RELEASE_VERSION=$version" >> "$GITHUB_ENV"

      - name: Move dist/nyaaup to nyaaup_linux
        run: mv dist/nyaaup nyaaup_linux

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag_name: ${{ env.RELEASE_VERSION }}
          body_path: changelog.txt
          files: nyaaup_linux

  windows-build:
    name: Windows
    runs-on: windows-latest
    needs: linux-build

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up libraries
        run: |
          python -m pip install pyinstaller
          python -m pip install .

      - name: Fetch version
        run: |
          $version=$(python -c "print(open('changelog.md', 'r').read().split('\n')[0].split(' ')[2].replace(':', ''))")
          echo "Version: $version"
          echo "RELEASE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build
        run: |
          pyinstaller --icon logo/logo.ico  -F __main__.py -n nyaaup

      - name: Move dist/nyaaup.exe to nyaaup.exe
        run: mv dist/nyaaup.exe nyaaup.exe

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag_name: ${{ env.RELEASE_VERSION }}
          files: nyaaup.exe

      - name: Workflow finished
        run: echo "Workflow finished."
