name: Build

on: workflow_dispatch

jobs:
  linux-build:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Set up libraries
        run: |
          python -m pip install wheel pyinstaller
          python -m pip install .

      - name: Build
        run: pyinstaller --icon logo/logo.ico -F nyaaup/__init__.py -n nyaaup

      - name: Fetch changelog and version
        id: get-info
        run: |
          VERSION_LINE=$(grep -m1 -E '^## \[[0-9]+\.[0-9]+\.[0-9]+\]' CHANGELOG.md)
          PACKAGE_VERSION=$(echo "$VERSION_LINE" | sed -E 's/^## \[([0-9]+\.[0-9]+\.[0-9]+)\].*/\1/')

          # Extract the changelog section corresponding to the version
          CHANGELOG_ENTRY=$(awk "/^## \\[$PACKAGE_VERSION\\]/ {found=1; next} /^## \\[/ {if (found) exit} found" CHANGELOG.md)

          echo "$CHANGELOG_ENTRY" > changelog.txt
          echo "version=$PACKAGE_VERSION" >> "$GITHUB_OUTPUT"
          echo "RELEASE_VERSION=$PACKAGE_VERSION" >> "$GITHUB_ENV"

      - name: Move dist/nyaaup to nyaaup_linux
        run: mv dist/nyaaup nyaaup_linux

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag_name: ${{ steps.get-info.outputs.version }}
          body_path: changelog.txt
          files: nyaaup_linux

  windows-build:
    name: Windows
    runs-on: windows-latest
    needs: linux-build

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Set up libraries
        run: |
          python -m pip install pyinstaller
          python -m pip install .

      - name: Fetch version
        run: |
          $version=python -c "import re; print(re.search(r'## \[([0-9.]+)', open('CHANGELOG.md').read()).group(1))"
          echo "Version: $version"
          echo "RELEASE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build
        run: |
          pyinstaller --icon logo/logo.ico -F nyaaup/__init__.py -n nyaaup --hidden-import=mal

      - name: Move dist/nyaaup.exe to nyaaup.exe
        run: mv dist/nyaaup.exe nyaaup.exe

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag_name: ${{ env.RELEASE_VERSION }}
          files: nyaaup.exe

      - name: Workflow finished
        run: echo "Workflow finished."
