name: Publish to PyPI and GitHub Release

on:
  workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    name: Build distributions
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tool
        run: python -m pip install --upgrade build

      - name: Build dists
        run: |
          SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
          python -m build

      - name: Generate hashes
        id: hash
        run: |
          cd dist
          echo "hashes=$(sha256sum * | base64 -w0)" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          if-no-files-found: error
          retention-days: 5

  provenance:
    needs: build
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    permissions:
      contents: write
      id-token: write
    with:
      base64-subjects: ${{ needs.build.outputs.hashes }}
      upload-assets: true
      compile-generator: true

  publish:  # ← aligned correctly here
    name: Publish to PyPI and GitHub
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build, provenance]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/nyaaup/

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Upload to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{
